### ISSUE TITLE
URLs containing '.' in the path result in a validation error

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#1011]
See [example results](http://standard.open-contracting.org/validator/data/4f9fb310-625a-43d7-86c7-22b4c110678e) from Honduras's SISOCS APP system.

Many URLs in the data include a period in the path, e.g.

> http://www.coalianza.net:81/mapas/pdf/02/40.%20Aprobación%20del%20Proyecto.pdf 

Those URLs work OK in a web browser and from a quick bit of research (e.g. [this thread](https://stackoverflow.com/questions/7555553/can-period-be-part-of-the-path-part-of-an-url)) periods in the path of a URL are OK.

Should we be flagging these as validation errors?

**Comment by robredpath** [comment]
Is it the dot or the port that's causing the issue?

**Comment by Bjwebb** [comment]
Actually, it's the `ó` that's the problem. This is permitted in IRIs but not URIs.

**Comment by robredpath** [comment]
Once we've got the nicer validation errors merged, we might want to revisit the text to make it more helpful in cases like this. 

We might want to consider whether the standard should use IRIs rather than URIs, but that's a whole other discussion (and may well not be technically feasible).

**Comment by duncandewhurst** [comment]
Aha, I wonder why I thought it was the period.

Should I tell them that since the link works in a browser it's not a problem, or would the use of IRI's cause problems for scripts or tools working with the data, e.g. something trying to fetch and display the document at the URL?

**Comment by robredpath** [comment]
It's difficult to predict the issues that using characters that aren't valid in a URI might cause. It would be preferable to just convert the IRI to a URI in the source system if at all possible - 
http://www.coalianza.net:81/mapas/pdf/02/40.%20Aprobaci%F3n%20del%20Proyecto.pdf is the URI equivalent of http://www.coalianza.net:81/mapas/pdf/02/40.%20Aprobación%20del%20Proyecto.pdf   (the ó can be encoded as %F3 in the same way as a space can be encoded as %20). However, it doesn't work in a browser, presumably because the server has some sort of security to check that the filename on disk is exactly the same as the last part of the URL. Which is eminently sensible. 

It might be fine. This data might only ever be used by people who can process it, but it means yet another exception when trying to make portable tooling for OCDS, and that other validation errors might go unnoticed/ignored. If someone is building a system to consume OCDS data, it's entirely reasonable that they might check for validity first, though, and reject invalid data. One might also assume in code that a URI field doesn't contain any multibyte (ie, UTF-8) characters, and thus the URL would become invalid when processed. 

So, if there's any way that they can make their URIs actual URIs, that'd be great. If there's some dev support needed, it's something that we can advise on (although it's also pretty well documented on StackOverflow!)

**Comment by timgdavies** [comment]
Thanks all for the notes on this. I've updated the Honduras report to cite that we require use of URIs. I don't think any actions for CoVE here right now.
