### ISSUE TITLE
OCDS: Small issue with linking to extended codelists

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1054]
If an extension adds codes, and then a later extension replaces all codes, the page has a `(+)` link next to the codelist name, even though that addition became irrelevant.

For example, with the JSON below, tariffs adds to documentType.csv, and then ppp replaces documentType.csv, such that the addition is of no consequence.

I believe the logic should be that when an extension replaces a codelist, any tracking of additions/subtractions from extensions applied earlier should be reset.

Original comment: https://github.com/OpenDataServices/cove/pull/1037#issuecomment-410405830

```json
{
  "version": "1.1",
  "uri": "https://github.com/open-contracting/sample-data/raw/1.1/fictional-example/ocds-213czf-000-00001-02-tender.json",
  "extensions": [
    "https://raw.githubusercontent.com/open-contracting/ocds_location_extension/master/extension.json",
    "https://raw.githubusercontent.com/open-contracting/ocds_tariffs_extension/master/extension.json",
    "https://raw.githubusercontent.com/open-contracting-extensions/ocds_ppp_extension/master/extension.json"
  ],
  "publishedDate": "2010-03-15T09:30:00Z",
  "publisher": {
    "name": "Open Data Services Co-operative Limited",
    "scheme": "GB-COH",
    "uid": "9506232.0",
    "uri": "http://data.companieshouse.gov.uk/doc/company/09506232"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-02-tender",
      "date": "2010-03-15T09:30:00Z",
      "initiationType": "ppp",
      "tag": [
        "tender"
      ],
      "tender": {
        "id": "ocds-213czf-000-00001-01-tender",
        "documents": [{
          "id": "foo",
          "documentType": "foo"
        }]
      }
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Separately, I noticed that Data Pipes errors on a valid CSV: http://datapipes.okfnlabs.org/csv/html/?url=https://raw.githubusercontent.com/open-contracting-extensions/ocds_ppp_extension/master/codelists/documentType.csv

**Comment by odscjames** [comment]
I have a failing test on this I think (branch in lib-cove-ocds).

The problem in fixing this is that in get_additional_codelist_values() it loops over

    for codelist_key in schema_obj.extended_codelist_urls.keys():

But that's not guaranteed to be in the order that the extensions are applied! schema_obj.extended_codelist_urls is populated in schema_obj.process_codelists by just setting keys.

If it was in order, I think this would be easy to fix by adding something like:  

    if codelist_key == codelist: 
         codelist_amend_urls = []

So we need something in order to loop over that lists the codelists in the order they are applied.


ps. This may be rubbish cos it's 5:40PM Friday, but it seems not great to me to use just the name of the codelist as a way to structure this data object. Surely if many extensions are applied, there could be a clash here?

**Comment by jpmckinney** [comment]
My understanding is that each value in extended_codelist_urls is a list of URLs of codelist patches, in the order in which codelist patches ought to be applied.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue with linking to extended codelists in CoVE](https://trello.com/c/31LsbyAX/31-issue-with-linking-to-extended-codelists-in-cove)

**Comment by jpmckinney** [comment]
Moved
