### ISSUE TITLE
Create a re-usable library containing data quality checks from CoVE [2.1]

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1063]

**Comment by odscjames** [comment]
This is in progress; there is a new library at https://github.com/open-contracting/lib-cove-ocds

The library is a pretty rough copy of the relevant code from CoVE; more work is needed over time to define a cleaner API and move responsibilities to the right place. In particular;

- It depends on Django because it uses some Django HTML stuff. This is not ideal, and over time we will make the library throw appropriate data that the Django app can catch and turn into HTML, thus removing the Django requirement from this library.
- There is a chunk of code that really should be in a central CoVE lib as it is used by several standards; the code in package libcore (and associated tests in libcore folder). This will be moved out to a new library probably in the next month, as we should be looking at a new standard in that time.


CoVE has code on master branch to use this which will be deployed soon. There is an open Pull Request on KingFisher to use this.

**Comment by jpmckinney** [comment]
Can be closed?

**Comment by BibianaC** [comment]
@odscjames is this issue still in progress?

**Comment by robredpath** [comment]
Closing as lib-cove-ocds is....basically this.
