### ISSUE TITLE
Data Load Workflow

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#111]
Do people have to step through fetch, convert, load to staging, load to live, or can they do it any order?

So e.g. can I fetch, convert, load to live and skip staging?

I guess I can fetch, convert, load to staging many times, before I load to live?

I'm wondering if disabling buttons could help with this (with bootstrap3 we can do <button type="submit" class="btn btn-default live-push" disabled>)

The other thing I'm trying to get my head round here is that live could be (many) 3 or 4 versions behind the one that is on staging say - do we need to capture that by more than just the date/time?

**Comment by Bjwebb** [comment]
Each of the steps should depend on the previous one. I think disabling buttons is a good suggestion.

Versions is indeed something we need to think about. Currently this problem isn't evident, because it's not yet possible to refetch data - when we implement this https://github.com/OpenDataServices/cove/issues/102 we'll need to consider versions.

**Comment by robredpath** [comment]
Closing due to #399 - this functionality will be removed in a future iteration
