### ISSUE TITLE
[1.1] Sketch out potential solutions to "new interface elements" 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1123]

**Comment by robredpath** [comment]
This is what I'm thinking for presenting errors in context. As an optional expand-ey bit for validation errors, and maybe additional checks. It'd show the row directly above the first error, and the first 3 errors. It'd have formatting that made it look as close to a spreadsheet as possible, so that it's easy for a user to make the link between the results and what they see in Excel. 

[Error in context.pdf](https://github.com/OpenDataServices/cove/files/2864833/Error.in.context.pdf)

**Comment by robredpath** [comment]
One potential addition to the validation section would be something like:


Your data contains 38 columns:

| From the standard | Not from the standard |
--- | ---
| 31 |  7  |

[ See which columns don't use the standard ]

Your data contains some validation errors 
| Columns with no validation errors | Columns with some validation errors | Columns with all validation errors in every cell |
--- | --- | ---
20 | 10 | 8

[ See validation errors ]

**Comment by robredpath** [comment]
@Bjwebb @BibianaC I think we talked about the 'adding words' parts separately, so I'm not putting anything about that here. Above are two ideas for adding new analysis/presentation of validation errors. Thoughts? 

(also cc @kindly )

**Comment by Bjwebb** [comment]
I think these both make sense as requests.

The challenge with both of these is getting the required spreadsheet information, from within CoVE itself (rather than flatten-tool). I think this will require returning extra data from flatten-tool, doing some fairly heavy wrangling of the existing sourcemap, or opening the spreadsheet in CoVE. In the second case talking about "columns" is more work, because there can be multiple columns for a single JSON field.

Also, what about when the first 3 errors are non-consecutive? I guess we might want an ellipsis, or one of these marks https://stackoverflow.com/questions/35627739/nvd3-line-chart-with-x-axis-break-want-to-include-broken-symbol

**Comment by robredpath** [comment]
We'll do the top one. The bottom one is harder, and IMO less important for publishers.
