### ISSUE TITLE
Add spreadsheet-style 'first 3 errors' tables to validation and additional checks

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1131]

**Comment by robredpath** [comment]
See https://github.com/OpenDataServices/cove/issues/1123#issuecomment-463600797

**Comment by Bjwebb** [comment]
WIP:

![screenshot from 2019-03-06 17-57-41](https://user-images.githubusercontent.com/634/53868509-8c241800-4039-11e9-9c60-70c6e49777a9.png)

**Comment by Bjwebb** [comment]
Here's a demo link - http://1131-spreadsheet-style-validation.cove-360-dev.default.threesixtygiving.uk0.bigv.io/?source_url=https://github.com/OpenDataServices/cove/raw/508dd3c63df3700a7fc264c8e0633536e4f23b8f/cove_360/fixtures/badfile_all_validation_errors_4_times.xlsx
"Missing Fields" doesn't look very good, so scroll down to "Incorrect Formats" to have a look at what it should be like.

![screenshot from 2019-03-07 16-05-02](https://user-images.githubusercontent.com/634/53938262-f5b42d00-40f2-11e9-94fc-04ff908bba28.png)

Clicking on the error count still brings up the old modal. The whole page looks the same for JSON files.

CSVs display a table, but without context atm. (Because I've gone down the, open the spreadsheet in cove route, and have only implemented xlsx so far). [[demo link](http://1131-spreadsheet-style-validation.cove-360-dev.default.threesixtygiving.uk0.bigv.io/?source_url=https://github.com/OpenDataServices/cove/raw/508dd3c63df3700a7fc264c8e0633536e4f23b8f/cove_360/fixtures/fundingproviders_grants_2_grants.csv)]

![screenshot from 2019-03-07 16-12-42](https://user-images.githubusercontent.com/634/53938522-df5aa100-40f3-11e9-8206-8f2f2d1c2f00.png)

"Missing Fields" does not look good because there's no column letters. We could revert back to the old view, but that would be inconsistent, or work out how to make a better table.

![screenshot from 2019-03-07 16-08-17](https://user-images.githubusercontent.com/634/53938351-517eb600-40f3-11e9-9af0-3368782004fd.png)

**Comment by Bjwebb** [comment]
Here's a suggestion for displaying the missing fields:
![screenshot from 2019-03-08 16-59-59](https://user-images.githubusercontent.com/634/54015671-ba356380-41c3-11e9-8ec2-247d34d7c8c4.png)

I'll probably pick a much lighter shade of red, and then also use that for the background for all the error cells.

**Comment by Bjwebb** [comment]
This should be more or less finished now:

Here's the demo link again - http://1131-spreadsheet-style-validation.cove-360-dev.default.threesixtygiving.uk0.bigv.io/?source_url=https://github.com/OpenDataServices/cove/raw/508dd3c63df3700a7fc264c8e0633536e4f23b8f/cove_360/fixtures/badfile_all_validation_errors_4_times.xlsx

![Screenshot from 2019-03-11 16-03-05](https://user-images.githubusercontent.com/634/54105708-34115b00-4417-11e9-95e7-29570192a7a3.png)

![Screenshot from 2019-03-11 16-04-54](https://user-images.githubusercontent.com/634/54105786-73d84280-4417-11e9-97e2-0199949d69e0.png)

**Comment by BibianaC** [comment]
@Bjwebb is this finished?

**Comment by Bjwebb** [comment]
Yes.
