### ISSUE TITLE
Quality feedback messages in 360Giving Quality Checks should give number of grants, not %, if it's a small number

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1200]
From @KDuerden

>  Quality feedback messages to give number of grants instead of percentage
> The messages for quality section are specific and framed as things to be looked at and potentially fixed, so a count makes more sense in this context. These tend to be feedback where there are few examples in large files means it is possible to have a 0% of x are y message 

<img width="859" alt="Zero percent Quality check" src="https://user-images.githubusercontent.com/641009/61729118-7b690a00-ad6e-11e9-9b93-69adf62d6ef4.PNG">

**Comment by robredpath** [comment]
For large data sets, it's much more informative to say "95% of your grants...."

When it's a very small number, 0% is misleading. We should just say the number. 

@michaelwood this could be a good candidate for you to look at as part of your iterative work, if it appeals!

**Comment by KDuerden** [comment]
On this one, I'm of the view that messages in the Quality section should always be numbers rather than percentages. This is because the expectation is these are issues to be fixed, so being specific makes sense to me. I don't agree that using a percentage is more effective on large data sets/one with high proportion of errors. Using a number can still convey the "something isn't right here" message effectively. 
In the Usefulness section I do think there's an arguement for % unless the result is eg 5% or below.

**Comment by BibianaC** [comment]
@KDuerden Is it ok for you if I work on this one?

**Comment by KDuerden** [comment]
Thanks @BibianaC that would be great!

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quality feedback messages in 360Giving Quality Checks should give number of grants, not %, if it's a small number](https://trello.com/c/ttCKtbdv/43-quality-feedback-messages-in-360giving-quality-checks-should-give-number-of-grants-not-if-its-a-small-number)
