### ISSUE TITLE
OCDS: A ‘user view’

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove#1213]
… which shows what a hypothetical user might see in the data

@duncandewhurst commented:

At the data use training the first reaction from KW and Nataliia on loading some data into the data review tool was "I don't know what to do with these errors"

Based on that we realised that a 'user' rather than 'publisher' view in the data review tool would be useful.

So instead of the feedback being along the lines of "amount is not a number. Check that the value doesn’t contain any characters other than 0-9 and dot (.). Number values should not be in quotes. " it could instead be:

"amount is not a number. If you need to use this field in a sum you may need to cast it to a numeric value"

Similarly, we could offer feedback on what to do about additional fields (check the publication policy) and extensions (review the extension documentation).

Or explain the consequences of duplicate items in arrays etc.

My vision for this is a toggle at the top of the Data Review Tool to switch between a publisher view and a user view of the results.

(Note that where we have produced guidance on using ocds data, such as in the OC4IDS docs and I think also in David's learning labs, we've generally suggested a first step is to check the data with the data review tool)

@jpmckinney commented:

> Substituting strings seems like an efficient approach with good reuse of existing software.

**Comment by jpmckinney** [comment]
I think it's best for the DRT to remain focused on serving publishers. As part of the data registry, we can scope what information to provide to the user about a given source's structural errors (likely very summarized).

**Comment by duncandewhurst** [comment]
The DRT is recommended as a tool for data users on https://www.open-contracting.org/data/data-use/#tools as well as in the places I mentioned above. Is there a plan to replace those mentions with the registry, once ready?

**Comment by jpmckinney** [comment]
Can you cite the specific reference? The only ones I find relate to publishers. The page mixes a bit of publisher vs user content, which needs tidying. I'm not sure what places above you mean.

> Data Review Tool: An online tool to report structural errors in OCDS data. It is primarily used by implementers of OCDS to check their conformance to the standard. Its library is used by Kingfisher to automatically check OCDS data after its collection.

**Comment by duncandewhurst** [comment]
It is listed in the tools gallery table under 'review', which I'd understood to be showing the tools available to support the different stages of using OCDS data.

![image](https://user-images.githubusercontent.com/19265814/92041907-3adf1b00-edcd-11ea-9334-8fe0daa6cc20.png)

Since the page is titled 'Using open contracting data' and the tools section follows the 'Tools and guidance for data use' heading, it looks like we are recommending the DRT as a tool for data users, even if the later text states that it is primarily used by implementers.

> I'm not sure what places above you mean.

I meant the places referenced in the issue description - the OC4IDS [guidance on using data from procurement systems](https://standard.open-contracting.org/infrastructure/latest/en/guidance/using/#using-data-from-procurement-systems-for-infrastructure-monitoring) and the [Getting & Exploring OCDS Data with Google Sheets learning lab](https://docs.google.com/document/d/1HF9sv_Q9DSsPEqBNtRnh-ub5HZOM_byJuTULIrlHrAo/edit#heading=h.c8t0paakhqy1). We also recommend it to users in other training and learning materials, but I'd need to check through them all to say exactly where.

**Comment by jpmckinney** [comment]
> Is there a plan to replace those mentions with the registry, once ready?

Yes, they will be replaced. Quite a lot of content will have to be updated when the registry is ready. I think it's a bit too early to catalog all the places that will need updates. The current mentions of the DRT are fine, as some users can find it helpful to see if there are structural errors, though the interface is not designed to support that use.

That said, the DRT cannot analyze complete datasets (unless the library is used directly... which users are not expected to know how to do), which is another reason for keeping the DRT focused on what it does well.

**Comment by jpmckinney** [comment]
For content changes to the data use page, please open a CRM issue for Andie's attention.
