### ISSUE TITLE
Error message: JSONDecodeError

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/cove#1280]
Valid Excel file of data that is unchanged from yesterday is getting error message:

> Error message: JSONDecodeError('Extra data: line 1 column 4 (char 3)',)
> If you think this is a bug, you can file an issue publicly on GitHub or get in touch via email.

https://dataquality.threesixtygiving.org/data/a92bac17-3d3c-4588-81a4-c458220fdd4e

I tested a few files before lunch and up to around 2pm today, and it was fine. Now only getting error messages.
Just tried testing some JSON data too, and got this error:

> Something went wrong with your request. This could be due to a bug in the application and/or the data you supplied.
> This error has been automatically reported to our development team. If you get in touch, please reference this error as 38c8b50ba6fb45cd88b29594bb8a6296.

https://dataquality.threesixtygiving.org/data/4e5b2359-5fc0-450d-8307-51dadca66c91

**Comment by Bjwebb** [comment]
This happened because GitHub was down. It should be fixed now.

We fetch the JSON schema from GitHub. This is itself a JSON file, hence the JSONDecodeError when the correct JSON was not returned.

Options here are: accept this breaking on the rare occasion that GitHub is down, or rewrite our code to fall back to the last good copy we downloaded.

More technical detail for this error can be found on Sentry:
* https://sentry.io/organizations/open-data-services/issues/1627336372/?project=46181
* https://sentry.io/organizations/open-data-services/issues/1627337332/?project=46181
* https://sentry.io/organizations/open-data-services/issues/1627345733/?project=46181

**Comment by KDuerden** [comment]
Thanks @Bjwebb - good to know the cause, we can recognise for future reference. Happy to leave it as acceptable risk caused by Github outage - no need to do a re-write, unless Github's uptime decreases significantly!
