### ISSUE TITLE
IATI CoVE: Activity ids with / confuses URL parser

### ISSUE THREAD

**Issue by notshi** [OpenDataServices/cove#1283]
Example url: http://d-portal.org/q.xml?aid=XM-OCHA-CBPF-AFG-19/3481/RA4/APC/NGO/14847
CoVE output: https://iati.cove.opendataservices.coop/data/e072d03e-7a3d-4b67-a1d1-3ec90e0e0d5d
Raised here: https://github.com/devinit/D-Portal/issues/576#issuecomment-640924815

**Comment by Bjwebb** [comment]
Thanks for the report.

Relevant piece of code: https://github.com/OpenDataServices/lib-cove-web/blob/5aa33cb098fa8bd7ab932bdd95fc5779b5d89fd3/cove/input/models.py#L67
We use a library for this. (Although, one we've been meaning to move away from, because its dependencies are deprecated). Not sure when I'll have chance to dig into this.

There's an unsatisfactory work around at the moment: save and upload.

A quick fix might be to add the `Content-Type` for XML (`text/xml`). Cove doesn't currently support this, but does support other Content-Types, so its just a matter of adding an entry to a dictionary.

**Comment by Bjwebb** [comment]
Looks like you've added the `text/html` header, and I've [just merged](https://github.com/OpenDataServices/cove/pull/1312) cove's  support of that, so this works now https://iati.cove.opendataservices.coop/?source_url=http://d-portal.org/q.xml?aid=XM-OCHA-CBPF-AFG-19/3481/RA4/APC/NGO/14847
