### ISSUE TITLE
Navigating beyond the (long) listing the Unique IDs 

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#158]
As a user, I find it difficult to navigate the initial (360) results page, as I have a long list of Unique grant IDs at the top of the page.  

I do not find this information immediately useful.  I would like a link to access this list, and would also like to know if my dataset contains any duplicate identifiers

**Comment by caprenter** [comment]
This feature was originally just for something to show. 

It could be useful in the case where there are many duplicates, so it's good to pinpoint the unique ones.

In the case where everything is unique, it's not much use.

For now, I'd suggest:
Keep the box, but remove the list. Instead of the list, just show the count.

This can be done quickly and easily, but does not need to be a permanent feature.
@stevieflow does that work for now?

**Comment by stevieflow** [comment]
@caprenter thanks, yes - agree

I wonder if it could be considered alongside https://github.com/OpenDataServices/cove/issues/159 too?

**Comment by caprenter** [comment]
Those issues are subtly different, but notifying of duplicates should get covered between these two tickets.

**Comment by kindly** [comment]
The new key metrics section does not have this issue
