### ISSUE TITLE
Error page should look more like an error

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#17]
There's various classes we can use from twitter bootstrap to make our error page look more like an error.

(To get an error page currently, you can upload a file that is not JSON or XLSX).

**Comment by caprenter** [comment]
Errors we have identified are:

* badly formed json
* unknown file type
* trying to access a data record for a file taht does not exists because:
a) primary key is not present
b) file has been deleted

These have been addressed in https://github.com/OpenDataServices/cove/commit/69e08d09f4b965f6e4c52791e16f90b64fc9c260
