### ISSUE TITLE
When was the file checked?

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#175]
Reviewing this: http://cove.opendataservices.coop/360/data/dc4366de-6143-4e51-a27e-66736e159e6d

I can't tell when the file was checked (other than it was in the last 7 days). Could a date be added for when the file was checked?

**Comment by Bjwebb** [comment]
Yes, I think it should be fairly straightforward to add the date when a file was uploaded/fetched.

Note that currently the validation/conversion/other analysis happens each time that page is loaded (so that if Cove has changed since the file was uploaded/fetched the page will be slightly different).

**Comment by Bjwebb** [comment]
As part of the work on this, we may also want to state when a file is going to be deleted: https://github.com/OpenDataServices/cove/issues/65

**Comment by caprenter** [comment]
It seems to me as though the 'Key Facts' box does contain/display when a file was uploaded now.

#65 also has a message (elsewhere on the page) that says files are deleted 7 days after they have been uploaded. 

I'd be happy to see this closed now. What do you think @ekoner

**Comment by Bjwebb** [comment]
Yes, we know state the date/time, but it looks like files are not being deleted properly: https://github.com/OpenDataServices/cove/issues/406
