### ISSUE TITLE
360 - clarify the line number of an individual validation issue

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#268]
When there is an instance of one validation issue eg:

> grants/60/recipientOrganization/0/postalCode

- work towards clarifying which line of the input file this is from - particularly when via a spreadsheet

**Comment by caprenter** [comment]
As you know (?) this is because, in order to do validation, we have to convert spreadsheets/csvs to json - which can then be validated against the schema.

When we do the conversion line numbers are not retained.

We are in discussions about validating CSVs and Spreadsheets as CSVs and Spreadsheets directly without conversion. As you can imagine this is a piece of work, and brings up questions about the authoritative versions of the standard, etc.

So addressing this user need is on our radar, but unlikely to be fixed quickly or easily.

**Comment by kindly** [comment]
See #246 as to separation of csv/json validation

**Comment by stevieflow** [comment]
This seems to be progressed in https://github.com/OpenDataServices/cove/issues/356 ?

**Comment by Bjwebb** [comment]
Yes, closing this one as I think it's captured in https://github.com/OpenDataServices/cove/issues/356
