### ISSUE TITLE
Conversion Warnings

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#369]
http://dev.cove.opendataservices.coop/360/data/6087f628-5c70-4d37-8653-6cf11571c633

I think this is about duplicate ID, but not too sure from:

> Discarded range with reserved name

> Conflict when merging field "title" for id "360G-gct-WB11296" in sheet grants: "New Youth Club for 12 - 15 year olds in Thatcham" != "Lambourn Imagination Library - Provision of 12 months x 250 children.". If you were not expecting merging you may have a duplicate ID.

> Conflict when merging field "description" for id "360G-gct-WB11296" in sheet grants: "New Youth Club for 12 - 15 year olds in Thatcham" != "Lambourn Imagination Library - Provision of 12 months x 250 children.". If you were not expecting merging you may have a duplicate ID.

> Conflict when merging field "amountDisbursed" for id "360G-gct-WB11296" in sheet grants: "1600" != "3375". If you were not expecting merging you may have a duplicate ID.

> Conflict when merging field "amountAwarded" for id "360G-gct-WB11296" in sheet grants: "1600" != "3375". If you were not expecting merging you may have a duplicate ID.

> Conflict when merging field "amountAppliedFor" for id "360G-gct-WB11296" in sheet grants: "4226" != "6250". If you were not expecting merging you may have a duplicate ID.

> Conflict when merging field "awardDate" for id "360G-gct-WB11296" in sheet grants: "2016-01-01T00:00:00+00:00" != "2016-01-29T00:00:00+00:00". If you were not expecting merging you may have a duplicate ID.

The Key Field Information box tends to suggest otherwise, I think:

> Grants: 68 
> Grant IDs: 68 

(linked to https://github.com/OpenDataServices/cove/issues/362)

**Comment by robredpath** [comment]
The error message is correct: 360G-gct-WB11296 is the grant ID given both in row 34 and row 62. There's 70 rows in the source spreadsheet; -1 for the headings gives 69 rows of grant data, so the 68 presumably is due to the non-uniqueness of that ID. 

That's a very long and verbose error message for what is fundamentally a single error, but annoyingly not one that we could easily transform with some string matching and manipulation. 

It would be very cool if we could parse those errors into a data structure so that we could do some more helpful analysis before reporting.

**Comment by caprenter** [comment]
This is not an error!

The behaviour is expected and the message is an attempt to explain what the application has done BECAUSE it has found duplicate ids

So....
If someone supplies a spreadsheet with duplicate id's then flatten tool now thinks that they have 'more to say about this grant' than can fit in a single row of a spreadsheet. e.g. 2 locations to report.
A data producer can duplicate that row, but change only the key information. However if you duplicate that row and supply info that cannot be merged, then the tool does it anyway, discards one of the values and then warns you about it.

What is interesting here is that the user, Steven, has managed to discover that he has a duplicate ID, but I'm not sure he can answer the question "If you were not expecting merging you may have a duplicate ID."

**Comment by robredpath** [comment]
I don't think we should get too hung up on the definition of an error :) 

It's interesting that both a mistake in the original data and an entirely intentional duplication of a grant look very similar, even though we want to handle them in very different ways. 

Would a good test to determine the difference be if the non-mergable information was different? Ie, in this case, it's two completely different rows, so it's a problem with the input data. Would a typical '2 locations to report' case have either blank or identical information in those fields?

**Comment by stevieflow** [comment]
OK - my bad in calling the issue "error", when CoVE labels it as "warnings"

I think this may also be linked to https://github.com/OpenDataServices/cove/issues/336 ?  I know @bjwebb did work on duplicates, but we didnt get to a resolve?

@caprenter states: 

> What is interesting here is that the user, Steven, has managed to discover that he has a duplicate ID, but I'm not sure he can answer the question "If you were not expecting merging you may have a duplicate ID."

It's true, I cannot answer that question, as I wasnt sure what it meant (as a user personna).  

What is less true is whether I have in fact discovered that I have a duplicate.  I look towards:

> Grants: 68 
> Grant IDs: 68

and can't see anything else to say that 69 records were in fact input into CoVE

IN terms of the dialogue / feedback in the Conversion warnings - I'd be interested to explore what other warnings I can discover. which are not just about duplicate IDs

**Comment by robredpath** [comment]
Why don't we update the standard at http://www.threesixtygiving.org/standard/reference/#toc-one-to-many-relationships to state that if using multiple rows, they MUST contain either the same data as the original row or be blank? We could then test for that as part of validation.

**Comment by Bjwebb** [comment]
Yes, I think that we could say that in the standard, and then these Python warnings are unambiguously "errors" (ie. something *is* wrong).

Just discussed with @kindly some possible approaches to displaying better messages about this in Cove. A quick summary is that I think we could generate some useful information about duplicates/merging during the conversion from the source map we're creating.

e.g. As part of the narrative of the page, we could be saying
> It looks like you supplied a single sheet spreadsheet. There are duplicate activity IDs. We've interpreted these as multiple rows about the same Grant (see "Multiple Rows" in http://www.threesixtygiving.org/standard/reference/#toc-one-to-many-relationships). If you were not expecting this the duplicate IDs are probably in error.

and link to a list of the duplicate IDs.

**Comment by robredpath** [comment]
Thanks @Bjwebb . Is the path to making a change to the 360 standard an issue in the ThreeSixtyGiving/standard repo?

**Comment by Bjwebb** [comment]
Yes, that's right.

**Comment by robredpath** [comment]
Added!

**Comment by robredpath** [comment]
https://github.com/ThreeSixtyGiving/standard/issues/149
