### ISSUE TITLE
Auto delete files

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/cove#38]
When people submit data to us (upload, paste, url) we should delete that data (and the derived converted data) after a period of x days (lets choose 7).

We will retain meta-data about that file e.g. was it an upload, url, or paste, when did it occur, did it convert or error, and maybe more...

BUT 7 days after upload/paste/pull from URL it (and it's derivatives) will be deleted from our server.

Once successfully uploaded, a page is created with a unique URL with 'explore' information and links to downloads. This URL could be used by people to share the results. After 7 days I expect that this page/URL will 404 (will it?)

Files that are uploaded, but fail to convert will  also need to be  deleted. (should this be immediately, or also after 7 days?) 
(I expect that there is no easily discoverable URL for these files, although if you know the filename and the code for this application it can easily be deduced)

Associated with this are the following tasks:

- [x] We need to tell people of our deletion policy in Terms and conditions
- [x] We need to tell people about our deletion policy on the front page/footer i.e. be explicit somewhere!
- [ ] We need to put a message on the 'explore' page showing when a file will be deleted (and that that URL/page will be come a 404 once the file is deleted)  ( we might also show 'time until deletion', but this is not necessary)
- [x] Provide a 404 message for that URL when the file is gone

**Comment by Bjwebb** [comment]
> Files that are uploaded, but fail to convert will also need to be deleted. (should this be immediately, or also after 7 days?) 

I'd suggest after 7 days - for consistency, and to make debugging easier than if immediately deleted.

> (I expect that there is no easily discoverable URL for these files, although if you know the filename and the code for this application it can easily be deduced)

I think we definitely want to try to make these urls less discoverable, probably by including the UUID that is used elsewhere if possible.


> After 7 days I expect that this page/URL will 404 (will it?)

Depends how we do the deletion. If we do keep the meta-data then we have the option of still displaying some information on the page (e.g. when the file was uploaded/uploaded, and possibly what the filename was). Even if we do this, we can make sure it still raises a 404 error code, for semantic nicety.

**Comment by Bjwebb** [comment]
In https://github.com/OpenDataServices/cove/commit/5bd5fccd5da6b95fd73ae35354b4fb2e2fb2fe8d I've added a management command to delete files older than 7 days (including any converted copies). http://dev.cove.opendataservices.coop/ocds/data/be0c2fd7-108b-4d78-bae2-5a8a096a8273 is what the 404 error message looks like.  The actual files are just served by apache, so that 404 message is just the default apache one - http://dev.cove.opendataservices.coop/media/be0c2fd7-108b-4d78-bae2-5a8a096a8273/tenders_releases_2_releases.json - it's possible to change this, but I don't think this is a priority for this iteration.

Additionally, this commit makes uploaded files less discoverable as they now always include the UUID.

Remaining tasks (in addition to those above):
- [ ] Add the command to cron in the deploy file https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/cove.sls

**Comment by Bjwebb** [comment]
Assigning @caprenter  to take a look at what I've done, and if you could add the text to the UI and T&Cs, that would be great too.

**Comment by caprenter** [comment]
@Bjwebb I suggest we can close this issue now, and recreate the outstanding task as a feature request. What do you think?

**Comment by Bjwebb** [comment]
Yes, split out now.
