### ISSUE TITLE
As a user, I'd like to access/see ALL the issues for a particular issue

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#393]
It it great that I can now see:

> Spreadsheet Location of first 3 errors

I can also understand that there are X instances for this error via "Error Count" column.

I understand, and appreciate, how this is laid out for me

However!  Where / how could I get the full list of errors ( i guess in both JSON and Spreadsheet report) ?

**Comment by robredpath** [comment]
@stevieflow we discussed this kind of functionality a bit last week - the thing we kept on hitting was how we can make this meaningful. It's hard to distinguish between a case where all (or almost all) of a particular error are due to the same thing (eg a date format being incorrect in a column) vs when someone has maybe 200 errors across 1500 lines and wants to download them all as basically a to-do list. 

I think we need to improve functionality around the case when an error is present on every (or almost every) line before this is very useful, but we think it's probably quite easy to offer it with the proviso that it might be a bit of an error dump. @kindly does that sound about right?

**Comment by timgdavies** [comment]
This *may* be a very bad idea, but is there a model in which a user might
download their spreadsheet again where we have added 'ERROR' columns next
to each col with errors and then highlight in those cols against the row
with the error what needs fixing.

Guidance to user could then be: correct all errors, remove the error col
and re-upload.

Of course, this only really works where the sheet is being hand-built, as
in any other scenario there would be data to correct upstream, so I'll
upgrade my statement to say this *probably is* a bad idea: but sharing in
case useful.

**Comment by stevieflow** [comment]
@timgdavies thanks.  Your "bad" idea might be more related to https://github.com/OpenDataServices/cove/issues/357 - but can also see how this issue can be too

@robredpath yes, understood, and can see the two different scenarios can be different use cases.  However, I think the main issue (to use the term) right now might be that I *can't* access any type of list.  If I can access the full list for each error, whether it one badly formatted date, or all records in a particular field - then at least I can then pick my next action(s)

There is also the middle case :+1: 
- I'm testing a file with 100 records
- I've got a particular error with 49 records (eg less than half so not all!)
- But, currently I can only gather info on where the first three occur

**Comment by robredpath** [comment]
@kindly this is the modal as we talked about

**Comment by Bjwebb** [comment]
These changes are now visible on the dev site http://dev.cove.opendataservices.coop/360/

**Comment by Bjwebb** [comment]
I think we've made changes to support Steven's use case here, so closing this issue. If anyone thinks there are specific remaining tasks, please to open new issues.
