### ISSUE TITLE
UWSGI threading warning

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#486]
Just spotted this in some sentry logs at https://sentry.io/open-data-services/cove/issues/172156444/
```
/home/cove/cove/.ve/lib/python3.4/site-packages/raven/utils/compat.py:59: Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport you are trying to use.  Please enable threading for uwsgi.  (Enable the "enable-threads" flag).
  warn(Warning('We detected the use of uwsgi with disabled threads.  '
```

We should probably enable-threads. Might be useful to have a chat with @idlemoor about.

**Comment by idlemoor** [comment]
Nice issue number :)

I've been turning a blind eye to that warning because we want to run just one thread per worker anyway (so that expensive requests are isolated and can be terminated). But thanks for the nudge. I'll actually investigate it instead of just ignorant neglect.

"Think about threading. If you do not need threads, do not enable them." -- uwsgi faq

But it seems there are two different things being talked about: threads within the uwsgi workers, and threads within the Python interpreter. Looks like 'enable-threads' is about the Python interpreter. If that's true, 'enable-threads' is probably a Good Thing for us.

I know you've tagged it 'next sprint', but we can roll out 'enable-threads' on the dev boxes at the same time that we do 'log-x-forwarded-for' and see what happens.

**Comment by Bjwebb** [comment]
I think http://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#a-note-on-python-threads is the best summary of what enable-threads does, and why we might want it in the python context.

**Comment by idlemoor** [comment]
When I read that this morning it made no sense at all.  Re-reading it now, however, yes I now see what you (and they) mean (thanks), although that may be just a passing delusion.

Let's Just Do It then.

**Comment by idlemoor** [comment]
u can haz pr :p
