### ISSUE TITLE
360Giving Data Quality Tool: Doesn't check for Identifier prefix

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/cove#501]
When an Identifier is provided, does it need to include the 360G-publisher- prefix? 

This is not picked up or reported by CoVE

**Comment by caprenter** [comment]
I guess you are talking about Grant Identifiers?

The [Identifiers guidance](http://www.threesixtygiving.org/standard/identifiers/#toc-register-a-prefix) says:
All registered prefixes should start with 360G unless you have been advised otherwise by the support team. 

I think this means CoVE can only look to issue warnings - or is the advice wrong. Are they all 360G?

**Comment by ekoner** [comment]
@caprenter they are so far, though I can see for certain publishers it may be desirable to retain their grant identifier but that risks it not being globally unique.

A warning would be grand.

**Comment by ekoner** [comment]
Related to #586

**Comment by stevieflow** [comment]
I think we have this covered through Additional Checks now - closing

Reopen if otherwise
