### ISSUE TITLE
Rework key field info into more narrative description of the data

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#516]

**Comment by robredpath** [comment]
Next task is for me to write the template for this.

**Comment by robredpath** [comment]
I'm actually wondering if this would make more sense at the top, in place of the headlines. But, either way, how about: 

"The data contains $grants grants, from $first_award_date.strftime('%d-%m-%Y) to $last_award_date.strftime('%d-%m-%Y). The grants range in value from $lowest_award_amount $currency_of_lowest_award to $highest_award_amount $currency_of_highest_award."

When writing this, I've found myself asking the question 'If I'm a user, what do I do if this info just isn't right', so I wonder if we need a 'looks wrong?' popup or link to blog post or something that guides people through common problems?

**Comment by Bjwebb** [comment]
We do currently have a common errors page http://dev.cove.opendataservices.coop/360/common_errors which is a similar idea.

**Comment by Bjwebb** [comment]
Is that all of a text, or just an initial sample? (ie. I notice there's quite a few numbers missing from that). The approach looks fine to me though.

Multiple currencies are tricky, because 1000 JPY is not more than 100 GBP. Our current layout isn't great for this either, but the fact the highest/lowest award amounts aren't currently displayed with a currency does give a clue that we're being naive.

**Comment by robredpath** [comment]
It's a starting point but I do think that some of the numbers currently in KFI would be better moved into 'potential issues' tests, especially the ones that aren't well-defined in the interface (what constitutes a 'good' recipient org ID prefix?). 

I did think about multiple currencies but I think it's an edge case in current usage. Do we get any multi-currency sheets passing through 360 CoVE? Maybe we could provide a smallest and largest for each currency if that occurs?
