### ISSUE TITLE
Explain download spreadsheet with titles after conversion from JSON

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#551]
It's potentially confusing that there are two 'download spreadsheet' links after conversion from JSON. We should add some explanatory text about what 'with titles' means.

**Comment by robredpath** [comment]
Internal issue 8340

**Comment by edugomez** [comment]
@robredpath I'm unable to reproduce this. Do you have a JSON file that on conversion generates 2 spreadsheet downloads?

**Comment by Bjwebb** [comment]
We've lost the second link because this if statement isn't true: https://github.com/OpenDataServices/cove/blob/master/cove_360/templates/cove_360/explore.html#L325, when it should be https://github.com/OpenDataServices/cove/blob/master/cove_360/settings.py#L45

**Comment by edugomez** [comment]
@Bjwebb thanks, will fix that

**Comment by edugomez** [comment]
@Bjwebb What are those titles for? Can't work it out. What should we say as explanatory text to differentiate between the two downloads?

**Comment by caprenter** [comment]
@stevieflow @timgdavies 
I'm just wondering whether or not we need to do this or not.
The issue is that CoVE will present users with a 'choice' of spreadsheet downloads if you provide 360Giving JSON. i.e. you can have a spreadsheet with either titles or fields as column headers (this is not well explained tho).

I think we've lost this distinction in the documentation/website - titles is the one 'everyone uses'. And links from http://www.threesixtygiving.org/standard/reference/ to the spreadsheet template only give people a direct download of the titles spreadsheet (whereas before you got to github and had to choose)

So I think rather than offer the user 2 versions, and have to try to explain why they are different, just  offer the titles.

Any reason not to?
It does make it hard for people to get a fields version (including ourselves) - although you can get it if you run flatten tool yourself.
Any other reasons - what do you think?

**Comment by timgdavies** [comment]
I would agree that we have moved very clearly towards titles in the case of 360 Giving, so the simplest option is just to offer 'Titles'

If we do offer the version with fields, it could be offered as an 'advanced' option (small text / or link to 'alternative formats' or something) because we can assume that users who want the fields version already understand what they are looking for...
