### ISSUE TITLE
Clickable share icon copies wrong link on dataquality.threesixtygiving.org

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#556]
"- Download and Share - I noticed that the clickable icon to copy doesnt copy the address displayed. It copies: http://cove.opendataservices.coop/360/data/8f0ee0a9-bf94-4a0e-8534-d7138261d2fa instead of https://dataquality.threesixtygiving.org/data/5c7f7258-2d1a-41a5-96a2-c3e721b14a0d"

**Comment by Bjwebb** [comment]
I think what actually happened here is that the copying was broken entirely, and you had the other link on your clipboard from previously.

Copying was broken because the JS wasn't being loaded over HTTP https://github.com/OpenDataServices/cove/pull/557

This should now be fixed, but I've not got quick access to a browser with flash installed. @robredpath Could you check?

**Comment by robredpath** [comment]
Confirmed fixed
