### ISSUE TITLE
Should the full version of schema be shown in the schema selector box?

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#578]
Currently, we show 1.0 and 1.1-dev. Should the 1.0 option be 1.0.2 (which is the actual version number) or just 1.0?

**Comment by timgdavies** [comment]
This relates to the version information we are asking users to provide in their files, which is currently just MAJOR.MINOR (because we want to always validate against the latest patch.

The concern is that if we show MAJOR.MINOR.PATCH people will put **this** in their version string.

However, I guess we have ways to handle that (failing validation for a file with MAJOR.MINOR.PATCH) and/or just telling them we ignored .PATCH and used the latest in the MAJOR.MINOR series to validate their data.

**Comment by jpmckinney** [comment]
I think the major.minor version is right, as we always want the most recent patch schema to be used, as it contains bug fixes.

So, I think this issue can be closed.
