### ISSUE TITLE
Add support for multiple CSV input

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#64]
This is multiple CSV "sheets" describing the data, not upload of multiple different datasets (e.g. for comparison) which would be a seperate issue.

We could provide a series of upload boxes for people to do this, or ask them to be uploaded in a zip archive.

**Comment by timgdavies** [comment]
I think this is where we should develop our multi-csv output format to be a full [Data Package](http://data.okfn.org/doc/data-package) - which would define an approach for providing the multiple files as a zip, and ideally, also with a .json file describing the various CSV files it contains.

That way we can talk about the multiple csv option being a datapackage.

We might choose to only warn, rather than reject, those which are just in a zip without the datapackage meta-data. 

We can describe to people how to easily zip their files if that becomes a usability challenge.

**Comment by robredpath** [comment]
After discussing with @Bjwebb , we're going to close this for now - although there are users producing multiple CSV files, the ones that we know of are using flatten-tool directly. If we come across people who would benefit from CoVE supporting this, we can certainly revisit this issue.
