### ISSUE TITLE
metatab - CoVE reports an error even when all extensions applied successfully

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#658]
CoVE reports a ```fetching failed``` error when uploading a spreadsheet with extensions specified in the ```Meta``` tab, even when all extensions are applied successfully ([example](http://dev.cove.opendataservices.coop/validator/data/1b1d063a-94f8-4dc8-aa00-8fd8ed837c91))

![image](https://cloud.githubusercontent.com/assets/19265814/25477197/9da56c1c-2b34-11e7-87bb-90adc20eaf5e.png)

**Comment by duncandewhurst** [comment]
@edugomez fyi

**Comment by Bjwebb** [comment]
This is due to the semicolon at the end of the cell - this creates an item in the extension list that is the empty string, which is the extension that's failed to fix. Removing this final semicolon should cause the error to go away.

We might want to change our code's behaviour, but possibly flatten-tool (don't generate a list with empty items) rather than this bit of Cove.

**Comment by edugomez** [comment]
Move to https://github.com/OpenDataServices/flatten-tool/issues/158 in flatten-tool
