### ISSUE TITLE
360 CoVE: Auto open the Data Summary Box

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#674]
There's an argument for auto opening the Data Summary Box for people - as it contains useful contextual information.  People may skip over it if they see the green tick

**Comment by robredpath** [comment]
It might make sense for this to be un-closable - more of a heading box than a content box.

**Comment by stevieflow** [comment]
> It might make sense for this to be un-closable - more of a heading box than a content box.

+1

**Comment by KDuerden** [comment]
'More information' section, which explains what happens to the file is it seems to be easy to miss. I just had email exchange with someone asking questions that 'More information' mostly answers. Could be all it needs is text in intro that directs people to check More info, rather than being open by default.
