### ISSUE TITLE
XMLSyntaxError when there are spaces in spreadsheet headings

### ISSUE THREAD

**Issue by tobybatch** [OpenDataServices/cove#705]
I'm on 635-sort-xml and I try to upload the activity XML from here: http://datastore.iatistandard.org/api/1/access/activity.csv

I get a XML validation error at:

```
XMLSyntaxError at /data/45a8afb1-21c5-423c-82ee-24213de1618c
error parsing attribute name, line 1, column 347 (unflattened.xml, line 1)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/data/45a8afb1-21c5-423c-82ee-24213de1618c
Django Version:	1.8.18
Exception Type:	XMLSyntaxError
Exception Value:	
error parsing attribute name, line 1, column 347 (unflattened.xml, line 1)
Exception Location:	/opt/cove/cove_iati/views.py in common_checks_context_iati, line 59
Python Executable:	/usr/local/bin/python3
Python Version:	3.6.1
Python Path:	
['/opt/cove',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/cove/src/flattentool',
 '/opt/cove/src/lxml/src']
Server time:	Mon, 12 Jun 2017 11:16:16 +0000
```

**Comment by tobybatch** [comment]
This was my error, the file extension was missing.  Renaming activity to activity.json cleared the above error but the system now recognises the data as a spread sheet.

```
We think you tried to supply a spreadsheet, but we failed to convert it to JSON.

Error message: Exception('The requested format is not available',)
```

**Comment by Bjwebb** [comment]
http://datastore.iatistandard.org/api/1/access/activity.csv is a CSV file, and should have a .csv extension. That's the extension I get when I download it, and I can reproduce your first error.

You're getting an XML error, because the CSV->XML is running, but produces an XML that isn't valid - http://635-sort-xml.dev.cove.opendataservices.coop/media/2d49b1c3-cadb-40b3-9a11-859b36459105/unflattened.xml . This is due to spaces in the headings of that CSV file, which become spaces in xml tag names, which isn't allowed.

**Comment by Bjwebb** [comment]
The same error in our internal logs - https://sentry.io/open-data-services/cove-dev/issues/278319020/
