### ISSUE TITLE
OCDS Validator: Permit validation with warning when version is specified as major.minor.patch

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove#715]
Currently the validator [stops validation proceeding](http://standard.open-contracting.org/validator/data/fb18192d-dada-41cc-bcf0-a24a29892771) when version is specified as major.minor.patch

![image](https://user-images.githubusercontent.com/19265814/27377318-87c5b222-566c-11e7-847d-ba6134d2b9a1.png)

Could we change this behaviour so that validation continues against the latest patch of the major.minor version specified, but a validation error or warning is given in the validator results?

**Comment by duncandewhurst** [comment]
related to #578

**Comment by robredpath** [comment]
@duncandewhurst I think it's potentially dangerous to assume that if you specify 1.0.1 then you get validated against 1.0.2, even with a warning. If you've specified 1.0.1 because you really meant 1.0.1 then you need to know that we didn't do what you asked for, and the validation results are potentially useless. If you specified 1.0.1 then you might mean 1.0, or you might have typo-ed 1.1...in which case we've done totally the wrong thing! 

However, we ultimately defer to what you and @timgdavies say on how we should present this messaging to users; if the behaviour you specify is what you really want, then we can do that (and I defer to @kindly, @edugomez and @Bjwebb to give an idea of how complex it is to do)

Would it be more helpful to specify what the permitted versions are in the error message, though, and to provide a more helpful error message - such as guidance that only MAJOR.MINOR should be specified?

**Comment by duncandewhurst** [comment]
@robredpath good points, though since we are only making bug fix changes in patch releases for OCDS I'm not sure how much danger would be introduced. I think the main issue is that providing a version specified as major.minor.patch shouldn't stop validation proceeding, I'm open to options for how we address that

**Comment by edugomez** [comment]
@duncandewhurst would this be acceptable?:
- For version in data following the pattern _major.minor.patch_:  the error is still displayed and recommends the user to get rid of the 'patch' part before re-running the cove. All versions available might also be displayed within the error box
- For version in data not recognised and not following the _major.minor.patch_ pattern (e.g. "version": "hello.world"): the error stays as it is now: (eg. "'hello.world'  is not a recognised ...)

Notice that neither option carries on with validation until the user modifies her (meta) data.  We could carry on with validation, however, in those cases in which the pattern for the field is right but not recognised (i.e. 1.4), in which case we will also warn the user of what we did.

**Comment by duncandewhurst** [comment]
@edugomez this sounds good, but with the addition of your suggestion:

> We could carry on with validation, however, in those cases in which the pattern for the field is right but not recognised (i.e. 1.4), in which case we will also warn the user of what we did (validation against 1.0.2, the current default version).

**Comment by Bjwebb** [comment]
This is now deployed on the dev : http://dev.cove.opendataservices.coop/validator/
