### ISSUE TITLE
360 CoVE - remove alpha header

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/cove#778]
Do we need this 

![alpha](https://user-images.githubusercontent.com/1209944/28534094-6587366e-7097-11e7-8727-361857e99933.png)

in place on https://dataquality.threesixtygiving.org/ still?  

--> @KDuerden @morchickit

**Comment by morchickit** [comment]
I believe we can remove it.

On 24 Jul 2017 5:42 p.m., "Steven Flower" <notifications@github.com> wrote:

Do we need this

[image: alpha]
<https://user-images.githubusercontent.com/1209944/28534094-6587366e-7097-11e7-8727-361857e99933.png>

in place on https://dataquality.threesixtygiving.org/ still?

--> @KDuerden <https://github.com/kduerden> @morchickit
<https://github.com/morchickit>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDataServices/cove/issues/778>, or mute the thread

**Comment by KDuerden** [comment]
Yes, agreed

**Comment by stevieflow** [comment]
@robredpath @Bjwebb can we do this?  The color contrast for the word Alpha also causes problems

**Comment by robredpath** [comment]
I'd be keen for us to have a header saying "This tool is under active development. Please report any problems or feedback on GitHub". I think it's important that users are encouraged to give feedback if there are any issues, but I appreciate that it has branding implications. Alternatively, it could be a call-to-action to contact support@, if we'd prefer? 

Thoughts @KDuerden @morchickit @stevieflow ?

**Comment by KDuerden** [comment]
I prefer generic call to contact support@.  
For the main audience for the tool Github bug reporting doesn't feel appropriate as it's more likely to be queries about the feedback messages. I'm already getting emails that raise these messages, framed as a 'problem', so if the method to give us feedback is made more obvious, I would expect that to prompt these kinds of queries/feeback, rather than technical issues.  If there are real technical glitches, then we can always signpost them to the Github to raise.

**Comment by stevieflow** [comment]
Can we get rid of the banner, and address the other issues about contact in a new discussion/action?

**Comment by stevieflow** [comment]
We added a header to the Registry: http://data.threesixtygiving.org/ 

Why dont we add similar to 360 CoVE?

I don't think we can tolerate the existing CoVE header much longer, given the message about Alpha, and then the fact that the link isn't viewable. Let's get this in line with the Registry, and then review signposting for feedback, separately

**Comment by KDuerden** [comment]
Only if it's very trivial amount of work. All this will get reviewed as part of CoVE developments soon, so I think it could also wait until then.

**Comment by robredpath** [comment]
I made this change as part of the work getting the new CoVE version ready for live

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build A Thing](https://trello.com/c/TbWLD5Zp/1-build-a-thing)

**Comment by stevieflow** [comment]
Hi @robredpath - did this make it to the latest deploy?

**Comment by robredpath** [comment]
This is now gone
