### ISSUE TITLE
Investigate integer/decimal conversion bug report

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#838]
We've heard (from @rory09 ? ) that integers become decimals when converted from OpenRefine. Or something like that. Assigning to Rory first to give an accurate description and example

**Comment by rory09** [comment]
Hi Rob,

This issue is most easily replicated with Google Docs:

* Create a new file
* Fill out IATI xpath headings and values including activity sector and various 'type' attributes (usually numerical)
* Download as .xslx
* Convert via CoVE

The resulting XML file will have '2.0' where the code provided in the sheet is '2', and this (I think) is to do with the way that Google sheets tries to decrease ambiguity by making a value 'cleary' a decemal when something like openpyxl (or something) parses the 'to_string' (or something) value from it to represent in XML.

I ca think of two possible fixes to this:

1. CoVE looks into the IATI schema for the version specified in the Meta tab, and then casts the value to the type associated with the element. This is a difficult, but I believe it's how 360 / OCDS do it.

2. When CoVE is handling a decimal value from a spreadsheet, then if it ends with ".0+" (in regex), then omit the decimal and subsequent zeros. This is a bit hacky, but might save a lot of time. and option 1 might be overkill if dates are broadly behaving. It would also mean we would be less tightly coupled to the IATI schema.

**Comment by Bjwebb** [comment]
I think in an ideal world we'd go for option 1. However, that could take quite a while to implement.

I think we should look at option 2 first, and see how easy/hacky that is. @kindly does that sound sensible?

**Comment by Bjwebb** [comment]
Here's a public example: https://docs.google.com/spreadsheets/d/1XKjJZoDbwq8SFpH6K6q6KGZ24JHciqxP0QBMQDiuzAk/edit#gid=0

**Comment by Bjwebb** [comment]
I think we can do this fairly nicely by trying to convert to int and then doing an equality test https://github.com/OpenDataServices/flatten-tool/commit/d629b1a56de58f92d6f249e38db337afe156bf76#diff-da34eb2b3d0a6bd6f7ca5fd1d20817f8R96

Here's a flatten-tool pull request: https://github.com/OpenDataServices/flatten-tool/pull/170

Here's an instance of CoVE with this flatten-tool commit, for you to test: http://838-float-int.dev.cove.opendataservices.coop/

**Comment by stevieflow** [comment]
> Here's an instance of CoVE with this flatten-tool commit, for you to test: http://838-float-int.dev.cove.opendataservices.coop/

Have tried this with some sample data (attached), derived from Google sheets.  This works well - checking the XML I can see that the code values are now as expected.  With LIVE, they convert to decimal

@rory09 worth checking

[CoVE IATI - short example.xlsx](https://github.com/OpenDataServices/cove/files/1332932/CoVE.IATI.-.short.example.xlsx)

**Comment by robredpath** [comment]
Thanks @stevieflow , closing as this looks like it's fixed now.

**Comment by robredpath** [comment]
Nope, the flatten-tool bit isn't merged yet. Re-opening.

**Comment by stevieflow** [comment]
Great - has this been merged into the live IATI CoVE though @robredpath @Bjwebb ?

**Comment by robredpath** [comment]
Not yet @stevieflow , that's one of the things for us to talk about this afternoon

**Comment by robredpath** [comment]
@Bjwebb - @stevieflow is keen for us to get this merged and deployed to live ASAP.

**Comment by Bjwebb** [comment]
Deployed now on http://iati.cove.opendataservices.coop/
