### ISSUE TITLE
Update CONTRIBUTING.md so external contributors know their PRs will fail secret data tests

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/cove#997]
`$TRAVIS_SECRET_FILES_PASSWORD` appears to be required.

**Comment by Bjwebb** [comment]
Yeah, this is a bit of a tricky one. That environment variable is deliberately a secret, so that we can pull in some real pre publication data, to check that behaves as expected.

For now, I'm just going to create a new pull request with a branch inside our org, so that all the tests can run. If we stick with this, then I guess a note in CONTRIBUTING.md would be a good idea.

**Comment by jpmckinney** [comment]
I'm not aware of any solution to this. Perhaps the issue title should be renamed to updating CONTRIBUTING.md as @Bjwebb suggested, and/or sequencing tests such that the failure relating to the secret occurs late?

**Comment by andylolz** [comment]
> sequencing tests such that the failure relating to the secret occurs late

I think this bit was addressed in 1f8361c84dcd95b0f8b9b19233815a7fb436afba.

> Perhaps the issue title should be renamed to updating CONTRIBUTING.md

Yeah, fair enough. Title updated.

/Unsubscribing because I don’t mind.

**Comment by jpmckinney** [comment]
Closed by #1205 ?

**Comment by robredpath** [comment]
This isn't an issue any more
